import dayjs from 'dayjs';
import PDFDocument from 'pdfkit';
import { storageService } from '../../services/storage';
import { aggregate } from './service';

/**
 * Resume PDF (R1-S3) — A4 portrait, built from the learner's verified record
 * (completed internships, project scores, certificates). Brand tokens match the
 * certificate (#1A73E8 / #202124 / #5F6368). Generated on demand, uploaded to
 * the private zone, served via a short-lived signed URL.
 */

const BRAND = '#1A73E8';
const INK = '#202124';
const MUTE = '#5F6368';
const LINE = '#DADCE0';

function pdfBuffer(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve) => {
    doc.on('data', (b: Buffer) => chunks.push(b));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });
  build(doc);
  doc.end();
  return done;
}

export async function buildResume(userId: number): Promise<{ url: string; expiresAt: string }> {
  const { owner, completed, certificates, stats } = await aggregate(userId);

  const pdf = await pdfBuffer((doc) => {
    const left = doc.page.margins.left;
    const right = doc.page.width - doc.page.margins.right;
    const width = right - left;

    // Header
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(24).text(owner.full_name, left, 48);
    if (owner.track) {
      doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(12).text(owner.track, { continued: false });
    }
    const contactBits = [owner.email].filter(Boolean) as string[];
    if (contactBits.length) {
      doc.fillColor(MUTE).font('Helvetica').fontSize(9.5).text(contactBits.join('  ·  '));
    }
    doc.moveDown(0.6);
    doc.moveTo(left, doc.y).lineTo(right, doc.y).lineWidth(1).strokeColor(BRAND).stroke();
    doc.moveDown(0.8);

    // Snapshot stats
    const statLine = [
      `${stats.completedInternships} internships completed`,
      `${stats.certificates} verified certificates`,
      `${stats.projectsShipped} projects shipped`,
      stats.averageScore !== null ? `avg score ${stats.averageScore}` : null,
    ].filter(Boolean).join('   •   ');
    doc.fillColor(MUTE).font('Helvetica').fontSize(10).text(statLine, { width });
    doc.moveDown(1);

    const sectionHeading = (label: string): void => {
      doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(12).text(label.toUpperCase(), { characterSpacing: 1 });
      doc.moveDown(0.2);
      doc.moveTo(left, doc.y).lineTo(right, doc.y).lineWidth(0.5).strokeColor(LINE).stroke();
      doc.moveDown(0.5);
    };

    // Completed internships
    sectionHeading('Internship Experience');
    if (completed.length === 0) {
      doc.fillColor(MUTE).font('Helvetica-Oblique').fontSize(10).text('No completed internships yet.');
    } else {
      for (const c of completed) {
        const score = c.project_score !== null ? `  ·  score ${Number(c.project_score)}` : '';
        doc.fillColor(INK).font('Helvetica-Bold').fontSize(11).text(c.title, { continued: false });
        const meta = [
          c.category,
          c.level,
          c.duration_weeks ? `${c.duration_weeks} weeks` : null,
          c.completed_at ? `completed ${dayjs(c.completed_at).format('MMM YYYY')}` : null,
        ].filter(Boolean).join('  ·  ');
        doc.fillColor(MUTE).font('Helvetica').fontSize(9.5).text(`${meta}${score}`);
        doc.moveDown(0.5);
      }
    }
    doc.moveDown(0.5);

    // Certificates
    sectionHeading('Verified Certificates');
    if (certificates.length === 0) {
      doc.fillColor(MUTE).font('Helvetica-Oblique').fontSize(10).text('No certificates issued yet.');
    } else {
      for (const cert of certificates) {
        doc.fillColor(INK).font('Helvetica-Bold').fontSize(10.5).text(cert.internship_title, { continued: true });
        doc.fillColor(MUTE).font('Helvetica').fontSize(9.5).text(
          `   ${cert.grade ? `Grade ${cert.grade} · ` : ''}${cert.certificate_no} · ${dayjs(cert.issued_at).format('DD MMM YYYY')}`,
        );
      }
    }

    // Footer
    doc.fillColor(MUTE).font('Helvetica').fontSize(8).text(
      `Generated by GI Internship · ${dayjs().format('DD MMM YYYY')} · all credentials independently verifiable`,
      left, doc.page.height - 56, { width, align: 'center' },
    );
  });

  const path = await storageService.upload('private', `resumes/user-${userId}.pdf`, pdf, 'application/pdf');
  return storageService.signedPrivateUrl(path);
}
