/**
 * Stable machine-readable error codes used in the JSON envelope.
 * Each code maps to exactly one HTTP status.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXHAUSTED: 'OTP_ATTEMPTS_EXHAUSTED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // Domain
  AGREEMENT_PENDING: 'AGREEMENT_PENDING',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  BATCH_FULL: 'BATCH_FULL',
  ENROLLMENT_CLOSED: 'ENROLLMENT_CLOSED',
  SUBMISSION_PENDING_REVIEW: 'SUBMISSION_PENDING_REVIEW',
  ATTEMPTS_EXHAUSTED: 'ATTEMPTS_EXHAUSTED',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  COUPON_INVALID: 'COUPON_INVALID',
  TOO_EARLY: 'TOO_EARLY',
  SESSION_ENDED: 'SESSION_ENDED',
  LESSON_LOCKED: 'LESSON_LOCKED',
  MAX_RESUBMITS: 'MAX_RESUBMITS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // AI (R2)
  AI_DISABLED: 'AI_DISABLED',
  AI_CAP_EXCEEDED: 'AI_CAP_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const errorStatusMap: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,

  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  OTP_INVALID: 400,
  OTP_EXPIRED: 410,
  OTP_ATTEMPTS_EXHAUSTED: 410,
  VERIFICATION_PENDING: 403,
  ACCOUNT_SUSPENDED: 403,

  AGREEMENT_PENDING: 409,
  ALREADY_ENROLLED: 409,
  BATCH_FULL: 409,
  ENROLLMENT_CLOSED: 409,
  SUBMISSION_PENDING_REVIEW: 409,
  ATTEMPTS_EXHAUSTED: 409,
  NOT_ELIGIBLE: 409,
  COUPON_INVALID: 400,
  TOO_EARLY: 409,
  SESSION_ENDED: 409,
  LESSON_LOCKED: 409,
  MAX_RESUBMITS: 409,
  PAYMENT_FAILED: 402,
  WEBHOOK_SIGNATURE_INVALID: 401,

  AI_DISABLED: 503,
  AI_CAP_EXCEEDED: 429,
};
